### ISSUE TITLE
When clicking on the stage to open the record, it tries to open an opportunity whatever the actual entity is

### ISSUE THREAD

**Issue by MscrmTools** [allandecastro/BusinessProcessFlowViewer#13]
Hi Allan,

See in debugger. There is an etn, but your code does not detect it when using e.etn, so it uses opportunity

![image](https://user-images.githubusercontent.com/10774317/94907029-d1bbf780-049f-11eb-95fb-39310c94ff73.png)

**Comment by allandecastro** [comment]
Hello,

I remember I had a problem with the name of the entity!
I tested it again and it seems to be a strange behaviour:

![image](https://user-images.githubusercontent.com/9749002/96188273-b5f42f00-0f3e-11eb-8222-074729d11f06.png)

![image](https://user-images.githubusercontent.com/9749002/96188292-c0162d80-0f3e-11eb-852f-788808db2644.png)

**Comment by allandecastro** [comment]
A bug is logged on the forum : https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/EntityReference-type-definition/m-p/444651#M1572
