### ISSUE TITLE
Control's parametersBPF char limit

### ISSUE THREAD

**Issue by Karuna2Karan** [allandecastro/BusinessProcessFlowViewer#2]
Hi Allan,

Very nice control. I was testing it in one of my environments, I noticed the 'parametersBPF' value has a character limitation also when I tried to change the option to 'Bind to a value on a field' it is not displaying any field from the entity. I have 3 custom BPFs in addition to the standard.

**Comment by KVerstuyft** [comment]
I'm having the same issue, it's not possible to add a different BPD due to the character limit..

**Comment by allandecastro** [comment]
Hello @Karuna2Karan and @KVerstuyft ,

Thank you for your interest to this component.
Indeed, it is a problem known to Microsoft but it cannot be solved.

Here is a link to a resolution method (via the inspector): https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/Problem-with-maximum-length-of-Input-parameters-which-are-of/td-p/288295
