### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by DaveStabilify** [allandecastro/BusinessProcessFlowViewer#21]
I can't enter the parameters that are needed. The text I enter is automatically truncated by the control.

**Comment by allandecastro** [comment]
Hello @DaveStabilify 

Thank you for your interest for this component.
Indeed, it is a problem known to Microsoft but it cannot be solved.

Here is a link to a resolution method (via the inspector): https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/Problem-with-maximum-length-of-Input-parameters-which-are-of/td-p/288295
