### ISSUE TITLE
No solution file to import component to D365

### ISSUE THREAD

**Issue by Tuffers81** [allandecastro/BusinessProcessFlowViewer#4]
Hi, I couldn't see the solution (.zip) file anywhere to download and import to D365...? Can you help me?

Love the concept and want to try this out :)

Thanks,
Richard

**Comment by allandecastro** [comment]
Hello @Tuffers81 ,

You can use this link : https://github.com/allandecastro/BusinessProcessFlowViewer/tree/master/Deployment/bin/Debug

Or build the component yourself following my instruction on the README.

Regards,
