### ISSUE TITLE
Control variables too long for the input box

### ISSUE THREAD

**Issue by MattPPMConsultant** [allandecastro/BusinessProcessFlowViewer#5]
Its not possible to enter the parametersBPF json in the Dynamics control dialogue box as the value is too long for the control on the edit parameters form..  This should be changed to take the value with out the need to re-compile the code.

**Comment by allandecastro** [comment]
Hello @MattPPMConsultant ,

Thank for your remark!
An issue was already posted here: https://github.com/allandecastro/BusinessProcessFlowViewer/issues/2

It's not a bug from my component but from MS.
